[package]
name = "debruijn"
version = "0.2.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
rand = "*"
smallvec = "*"
bit-set = "0.4.0"
itertools = ">=0.6"
pdqsort = "*"

[dependencies.extprim]
version = "^1.4.0"
features = ["serde"]

[dependencies.num]
version = "*"
default-features = false 
features = ["serde"]

[dependencies.log]
version = "^0.3.7"
features = ["release_max_level_info"]
